aes:
  encryption:
    key: "FDC6D3DDD1BEA52F013A574FD8B27278"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/Institute
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 40000
      maxLifetime: 50000
      maximumIdle: 5
      poolName: Institute

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: Institute
    generate-ddl: true

server:
  port: 8989
  servlet:
    context-path: /institute

application:
  connection-timeout: 5000
  read-timeout: 5000